# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  include:
    - DRUPAL: "7"
      TK: "3.3.4"
      ID: "TK3D7"
      COMPOSER: "1"
    - DRUPAL: "8"
      TK: "4.4.6"
      ID: "TK4D8"
      COMPOSER: "2"
    - DRUPAL: "9"
      TK: "8.2.2"
      ID: "TK8D9"
      COMPOSER: "2"

# ==============================================================================
# Main services
# ==============================================================================
services:
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-${MYSQL_VERSION=5.7}
    command: --innodb-log-file_size=128M --max-allowed-packet=1G --innodb-buffer-pool-size=512M
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  grab-site:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: prepare
    commands:
      - echo PROJECT=$(pwd)
      - rm -rf /test/toolkit/*
      - rm -rf .drone.yml
      - rm -rf .gitignore
      - rm -rf .git
      - git init
      - git remote add ${ID} https://github.com/drupal-composer/drupal-project.git
      - git fetch ${ID}
      - git checkout -b ${DRUPAL}.x --track ${ID}/${DRUPAL}.x # origin/master is clone's default
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Prepare section:
  # ============================================================================
  set-composer:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: prepare
    commands:
      - composer self-update --${COMPOSER}

  # ============================================================================
  # Setup section:
  # ============================================================================
  list-files:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: setup
    secrets: [ github_api_token ]
    commands:
      - ls -lah

  # ============================================================================
  # Setup section:
  # ============================================================================
  install-drupal:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: setup
    secrets: [ github_api_token ]
    commands:
      - composer install

  # ============================================================================
  # Build section:
  # ============================================================================
  install-toolkit:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: build
    secrets: [ github_api_token ]
    commands:
      - composer require --dev ec-europa/toolkit:${TK}
