workspace:
  base: /test
  path: default

pipeline:

  # https://github.com/ec-europa/docker-fpfis/tree/release/drone-plugin-default-message#default-message-plugin
  default-message:
    image: fpfis/default-message:1.2.0
    message_text: "This branch is used as inventory, no special CI need."
    exit_code: 0